// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/knabben/sawtooth-operator/pkg/apis/sawtooth/v1alpha1.Sawtooth":       schema_pkg_apis_sawtooth_v1alpha1_Sawtooth(ref),
		"github.com/knabben/sawtooth-operator/pkg/apis/sawtooth/v1alpha1.SawtoothSpec":   schema_pkg_apis_sawtooth_v1alpha1_SawtoothSpec(ref),
		"github.com/knabben/sawtooth-operator/pkg/apis/sawtooth/v1alpha1.SawtoothStatus": schema_pkg_apis_sawtooth_v1alpha1_SawtoothStatus(ref),
	}
}

func schema_pkg_apis_sawtooth_v1alpha1_Sawtooth(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Sawtooth is the Schema for the sawtooths API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/knabben/sawtooth-operator/pkg/apis/sawtooth/v1alpha1.SawtoothSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/knabben/sawtooth-operator/pkg/apis/sawtooth/v1alpha1.SawtoothStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/knabben/sawtooth-operator/pkg/apis/sawtooth/v1alpha1.SawtoothSpec", "github.com/knabben/sawtooth-operator/pkg/apis/sawtooth/v1alpha1.SawtoothStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_sawtooth_v1alpha1_SawtoothSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SawtoothSpec defines the desired state of Sawtooth",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"nodes": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
					"version": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"consensus": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"nodes", "version", "consensus"},
			},
		},
	}
}

func schema_pkg_apis_sawtooth_v1alpha1_SawtoothStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SawtoothStatus defines the observed state of Sawtooth",
				Type:        []string{"object"},
			},
		},
	}
}
